#server:
#  port: 8001
#spring:
#  application:
#    name: javaline-service
#eurekalogin:
#  username: username
#  password: password
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://${eurekalogin.username}:${eurekalogin.password}@localhost:8761/eureka/
logging:
  level: info
  config: classpath:logback-spring.xml