#
#eurekalogin:
#  username: username
#  password: password
#
#eureka:
#  client:
#    service-url: 
#      defaultZone: http://${eurekalogin.username}:${eurekalogin.password}@localhost:8761/eureka/
#server:
#  port: 80
#spring:
#  application:
#    name: zuul
#zuul:
#  routes: 
#    api1:
#      path: /line/**
#      serviceId: javaline
#      
#---
#logging:
#  config: classpath:logback-spring.xml
  